phases:

# Build all configurations for Windows
- template: /build/ci/phase-template.yml
  parameters:
    name: Windows
    buildMatrix:
      Py36:
        _buildScript: build.cmd
        _configuration: RlsWinPy3.6
      Py35:
        _buildScript: build.cmd
        _configuration: RlsWinPy3.5
      Py27:
        _buildScript: build27.cmd
        _configuration: RlsWinPy2.7
    buildQueue:
      name: Hosted VS2017

# Build all configurations for Mac
- template: /build/ci/phase-template.yml
  parameters:
    name: Mac
    buildMatrix:
      Py36:
        _buildScript: ./build.sh
        _configuration: RlsMacPy3.6
      Py35:
        _buildScript: ./build.sh
        _configuration: RlsMacPy3.5
      Py27:
        _buildScript: ./build27.sh
        _configuration: RlsMacPy2.7
    buildQueue:
      name: Hosted macOS

# Build all configurations for Linux
  # Run tests on Ubuntu16
- template: /build/ci/phase-template.yml
  parameters:
    name: Linux_Ubuntu16
    testDistro: ubuntu16
    buildMatrix:
      Py36:
        _buildScript: ./build.sh
        _configuration: RlsLinPy3.6
      Py35:
        _buildScript: ./build.sh
        _configuration: RlsLinPy3.5
      Py27:
        _buildScript: ./build27.sh
        _configuration: RlsLinPy2.7
    buildQueue:
      name: Hosted Ubuntu 1604
  # Run tests on Ubuntu14
- template: /build/ci/phase-template.yml
  parameters:
    name: Linux_Ubuntu14
    testDistro: ubuntu14
    buildMatrix:
      Py36:
        _buildScript: ./build.sh
        _configuration: RlsLinPy3.6
      Py35:
        _buildScript: ./build.sh
        _configuration: RlsLinPy3.5
      Py27:
        _buildScript: ./build27.sh
        _configuration: RlsLinPy2.7
    buildQueue:
      name: Hosted Ubuntu 1604
  # Run tests on CentOS7
- template: /build/ci/phase-template.yml
  parameters:
    name: Linux_CentOS7
    testDistro: centos7
    buildMatrix:
      Py36:
        _buildScript: ./build.sh
        _configuration: RlsLinPy3.6
      Py35:
        _buildScript: ./build.sh
        _configuration: RlsLinPy3.5
      Py27:
        _buildScript: ./build27.sh
        _configuration: RlsLinPy2.7
    buildQueue:
      name: Hosted Ubuntu 1604